### ISSUE TITLE
react-static start fails

### ISSUE THREAD

**Issue by LeslieJohnson** [tannerlinsley/tannerlinsley.com#1]
```$ react-static start
Starting Development Server...
  Error: The following error occurred in the plugin: "react-static-plugin-mdx"

  Error: Unknown plugin hooks: "config" found in plugin: /home/les/src/play/tannerlinsley.com/node_modules/react-static-plugin-mdx
```
I'm running Arch Linux, Node 11.6.0. I'm able to run the `react-static` demo, but not this site.

**Comment by tannerlinsley** [comment]
Needs to upgrade to the latest version of React Static. Run `yarn upgrade react-static`

**Comment by LeslieJohnson** [comment]
Same error. What does work though, is if I use `react-static create` and select the `git` template with this project. I can live with that.

**Comment by tannerlinsley** [comment]
Interesting. I'll have to dive into this later.

**Comment by tannerlinsley** [comment]
Not using React Static any more.
